/** ATTENTION: This file is autogenerated by AssemblyScript compiler, please do not edit manually. */
declare namespace __AdaptedExports {
  /** Exported memory */
  export const memory: WebAssembly.Memory;
  /**
   * index.as/add
   * @param a `i32`
   * @param b `i32`
   * @returns `i32`
   */
  export function add(a: number, b: number): number;
}
/** Instantiates the compiled WebAssembly module with the given imports. */
export declare function instantiate(module: WebAssembly.Module, imports: {
  env: unknown,
}): Promise<typeof __AdaptedExports>;

/** Shape of the WASM module compiled from AssemblyScript */
export type WasmModule = typeof __AdaptedExports;