// import test from "tape";
// import * as fs from "fs";
// import { writeDeclarationFile } from "./write-declaration-file";
// import mock from "mock-fs";
// // import { dbg } from "../dbg";
//
// test("writeDeclarationFile should write the declaration file correctly", (t) => {
//   mock({ "./src": {} });
//
//   // dbg.setEnabled(true);   // enable debug output
//   // TEST 1
//   writeDeclarationFile(" Custom declarations ", `./src/wasm-module.d.ts`);
//   const isFileCreated = fs.existsSync("./src/wasm-module.d.ts");
//   t.ok(isFileCreated, "File `wasm-module.d.ts` should be created in `./src`");
//
//   // TEST 2
//   t.comment("Make sure the content of `wasm-module.d.ts` is correct");
//   const data = fs.readFileSync("./src/wasm-module.d.ts", {
//     encoding: "utf-8",
//   });
//
//   t.equals(
//     data,
//     "/** ATTENTION: This file is autogenerated by AssemblyScript compiler, please do not edit manually. */\n Custom declarations \n/** Shape of the WASM module compiled from AssemblyScript */\nexport type WasmModule = typeof __AdaptedExports;",
//     "The content of `wasm-module.d.ts` is correct"
//   );
//
//   mock.restore();
//   t.end();
//
//   // dbg.setEnabled(false); // disable debug output
// });
