import * as fs from "fs";
import { dbg } from "../dbg";

const PREF = "[ASC][WDF]";

/**
 * Write types for the WASM module to the disk.
 * The `.d.ts` file should contain all the signatures of callable function and accessible properties of the WASM module.
 * @param content
 */
export function writeDeclarationFile(content: string) {
  if (!content) {
    dbg.error(`${PREF} '.d.ts' has no content!`);
    return;
  }
  const fileName = `./assembly/../wasm-module.d.ts`;

  const topComment = `/** ATTENTION: This file is autogenerated by AssemblyScript compiler, please do not edit manually. */`;
  const typeExport = `/** Shape of the WASM module compiled from AssemblyScript */\nexport type WasmModule = typeof __AdaptedExports;`;
  const declarationFileContent = `${topComment}\n${content}\n${typeExport}`;

  try {
    fs.writeFileSync(fileName, declarationFileContent);
    dbg.log(`${PREF} '.d.ts' file written successfully!`);
  } catch (error) {
    dbg.error(`${PREF} Error writing to file: ${error}`);
  }
}
