/**
 * Extends the JS glue generated by TSC with the WASM compilation code.
 * @param jsCode
 * @param isNode
 * @return {string}
 */
export function extendJsCode(jsCode, isNode) {
  // FIXME: "output.wasm" should not be hardcoded! Pass it from the outside
  return (
    jsCode +
    `let instance = null;
      export async function initWasm() {
        if (instance == null) {
          let url = new URL("output.wasm", import.meta.url);
          instance = await instantiate(
            await ${
              isNode
                ? `WebAssembly.compile(await (await import("node:fs/promises")).readFile(url))`
                : `WebAssembly.compileStreaming(fetch(url))`
            },
            {}
          );
        }
        return instance;
      }`
  );
}
